create table personalidades(
    id serial primary key,
    nome varchar,
    historia varchar
);

-- NOME DE RUAS DE NITEROI E A HISTORIA DO HOMENAGEADO 
INSERT INTO personalidades(nome, historia) VALUES
    ('Paulo Gustavo', 'Paulo Gustavo foi um ator e comediante nascido em Niterói, famoso por sua atuação no teatro, televisão e cinema. Seu trabalho em filmes como "Minha Mãe é uma Peça" lhe garantiu grande reconhecimento no Brasil. Sua morte, em 2021, vítima de COVID-19, causou grande comoção no país.'),
    ('Nísia Floresta', 'Nísia Floresta, nascida no Rio Grande do Norte, foi uma escritora e educadora brasileira, pioneira na luta pelos direitos das mulheres e pela educação feminina. Ela passou parte de sua vida em Niterói, onde teve grande influência na formação intelectual da cidade no século XIX.'),
    ('Carlos Drummond de Andrade', 'Carlos Drummond de Andrade foi um dos maiores poetas brasileiros do século XX. Natural de Itabira, ele teve grande relação com Niterói durante sua juventude, sendo um dos maiores nomes da literatura brasileira. Seu legado como escritor e sua obra, que aborda questões sociais e existenciais, é amplamente reconhecido.'),
    ('Getúlio Vargas', 'Getúlio Vargas foi presidente do Brasil em dois períodos distintos, sendo um dos maiores nomes da história política brasileira. Sua atuação foi fundamental para a criação de direitos trabalhistas no Brasil e para a modernização da economia brasileira, influenciando profundamente a política nacional, incluindo a cidade de Niterói.'),
    ('Maria Lúcia Lins', 'Maria Lúcia Lins foi uma educadora e escritora, reconhecida pelo seu trabalho na área da educação, especialmente com crianças e jovens, sendo uma das primeiras a desenvolver projetos educativos na cidade de Niterói. Sua rua em Niterói a homenageia pela sua contribuição à cultura e educação no município.'),
    ('Quintino Bocaiúva', 'Quintino Bocaiúva foi um jornalista, político e ativista republicano brasileiro, que teve um papel fundamental na proclamação da República. Com forte atuação no campo das ideias e no jornalismo, ele é uma figura histórica de grande relevância no Brasil, especialmente durante o período de transição do Império para a República. A rua em Niterói é uma homenagem a sua contribuição para a história do país.'),
    ('Nóbrega', 'Francisco de Nóbrega foi um militar e político brasileiro, que teve papel importante na história do Brasil durante o século XIX. Ele foi um dos grandes defensores da independência do Brasil e participou de várias missões militares no país. Sua atuação no campo político e militar é lembrada como fundamental para a consolidação da independência nacional.'),
    ('Gastão Gonçalves', 'Gastão Gonçalves foi um importante empresário e político brasileiro, conhecido por seu trabalho em prol da economia e do desenvolvimento de Niterói. Ele teve destaque por sua atuação na área de comércio e foi muito influente na região, contribuindo para a modernização da cidade e no fortalecimento de suas instituições durante o século XX.'),
    ('Miguel de Frias', 'Miguel de Frias foi um intelectual e advogado brasileiro, sendo uma figura importante na história jurídica e educacional de Niterói. Ele também teve grande influência no campo das artes e da literatura na cidade. Sua rua em Niterói homenageia sua contribuição para a cultura e o ensino na região, tendo sido um dos responsáveis pelo desenvolvimento do sistema educacional local.'),
    ('Conceição', 'Nossa Senhora da Conceição, uma das mais importantes figuras da Igreja Católica no Brasil. A devoção à Nossa Senhora da Conceição foi um marco na história religiosa e cultural de diversas cidades brasileiras, incluindo Niterói, que tem uma forte tradição católica. Esta rua reflete a importância da figura religiosa na formação cultural e histórica da cidade.'),
    ('Zilmar de Oliveira', 'Zilmar de Oliveira foi uma importante ativista e defensora dos direitos humanos, especialmente na luta pela educação e justiça social. Sua trajetória foi marcada por seu trabalho em prol das populações mais vulneráveis, com forte atuação em políticas de inclusão social e cultural.');
